### ISSUE TITLE
Possible to inject HTML/CSS

### ISSUE THREAD

**Issue by ssddanbrown** [stuartajd/getURL#1]
Through the right link it's possible to inject HTML & CSS content into the popup.

[Here's a test link](https://google.com?test=%3Cstyle%3Ebody%7Bbackground%3Apink%3B%7D*%7Btransform%3Arotate(45deg)%7D*%3Ahover%7Btransform%3Arotate(900deg)%3Btransition%3Aall+linear+10s%7D%3C%2Fstyle%3E%3Cimg+src%3D%22https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F2758562730%2Fa70bf848eb2351d3be7e440e076d9a13.jpeg%22+width%3D%22100%22%3E)

JS injection doesn't seem possible though.

**Comment by stuartajd** [comment]
Thank you for letting me know!
I've fixed this in https://github.com/stuartajd/getURL/commit/7b90cde0408eb2f6b0673fe7b2e9847b4cc9e048
Should be available through the Chrome Store shortly. (1.0.4 update)
